[package]
name = "github-issues"
version = "0.1.1"
authors = ["Arnau Siches <arnau@ustwo.com>"]

[dependencies]
curl = "0.2"
docopt = "0.6"
rustc-serialize = "0.3"
csv = "0.14"
log = "0.3"
regex = "0.1"

[[bin]]
name = "github-issues"
test = false
doc = false

[[test]]
name = "lib"
